name: Update wakatime stats

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "30 18 * * *"
jobs:
  build:
    name: Update-waka-stats
    runs-on: ubuntu-latest
    env:
      WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      UPDATE_OPTION: GIST_AND_MARKDOWN
      MARKDOWN_FILE: README.md
      GIST_ID: b7ae11ae916cc3eb529c054e1afad6e2
      GIST_BARSTYLE: SOLIDLT
      GIST_BARLENGTH: -1
      GIST_TIMESTYLE: LONG
    steps:
      - uses: actions/checkout@master
      - name: Install
        run: npm ci
      - name: Update gist
        run: node ./index.js > "README.md" --unhandled-rejections=strict
      - name: Commit and push if changed
        run: |-
          git diff
          git config --global user.email "bob@users.noreply.github.com"
          git config --global user.name "vsedov"
          git add -A
          git commit -m "Updated content" || exit 0
          git push
